### ISSUE TITLE
Hoofdstuk CRS en hoofdstuk Basisdata van volgorde wisselen

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/wpungii#10]
Waarom CRS eerst? Ik zou beginnen met "Basisdata", dat is een algemener onderwerp. CRS is een specifieker aspect dat speelt bij de geometrische representatie van basisdata. Dus ik zou beginnen met Basisdata, dan CRS, dan Ontsluiting en Governance.

**Comment by frisopenninga** [comment]
Overgenomen. Oorspronkelijke volgorde was afkomstig uit stuk uit GI-Beraad, maar omdraaiing is inderdaad logischer.
