### ISSUE TITLE
3.4: opsomming oplossingen is dubbelop

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/wpungii#11]
In paragraaf [3.4 Gebruikers verwachten volledigere en actuelere data](https://geonovum.github.io/wpungii/#gebruikers-verwachten-volledigere-en-actuelere-data) staat een opsomming van oplossingen waarop vaker zal worden ingezet, maar die opsomming wordt voorafgegaan door een lange zin waarin de oplossingen ook al aangestipt worden inclusief voorbeelden. Dat zou ik inkorten; de oplossingen worden helder uiteengezet in de opsomming, in de zin daarvóór hoef je ze niet ook te noemen. Of eventueel die introducerende zin flink inkorten (voorbeelden eruit etc). Het is op deze manier lastig te lezen.

**Comment by frisopenninga** [comment]
Goed gespot, die opsomming had ik toegevoegd omdat ik de zin ervoor te lang (en tegelijk inhoudelijk nog steeds te beknopt) vond, maar ik was inderdaad vergeten om die zin vervolgens aan te passen. Opgelost.
