### ISSUE TITLE
Volgorde paragrafen in hfd 4

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/wpungii#12]
Suggestie: [3.4](https://geonovum.github.io/wpungii/#gebruikers-verwachten-volledigere-en-actuelere-data) als eerste paragraaf van [hoofdstuk 3](https://geonovum.github.io/wpungii/#Data) neerzetten. Eerst over de inwinning, dan de harmonisatie etc.

**Comment by frisopenninga** [comment]
Overgenomen.
