### ISSUE TITLE
4.2: Linked data als meer dan een inspiratiebron

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/wpungii#15]
In [paragraaf 4.2](https://geonovum.github.io/wpungii/#ontsluiten-van-basisdata) wordt linked data genoemd als een inspiratiebron, maar het is meer dan alleen een inspiratiebron. Ik zou zeggen "voor die gevallen is de aanpak van linked open data _een goede keuze_." Ook zou ik toevoegen, na de zin over linken naar semantiek: "_Ook is het mogelijk relaties te leggen van de ene instantie naar andere instanties, die zich in andere datasets kunnen bevinden, waardoor de data interoperabiliteit flink verhoogd wordt_" - zoiets.

**Comment by frisopenninga** [comment]
Overgenomen
