### ISSUE TITLE
4.2: meer schrijven over lichtere formaten

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/wpungii#16]
In [paragraaf 4.2](https://geonovum.github.io/wpungii/#ontsluiten-van-basisdata) worden lichtere formaten maar heel kort aangestipt. Toch is dit ook een belangrijke ontwikkeling; het verschil met de NGII 1.0 zit 'm er misschien vooral in dat er nu _meerdere_ valide geo-formaten zijn waaruit men moet kiezen en er ook situaties zullen zijn waarin je dezelfde data in meerdere formaten aanbiedt, omdat er verschillende gebruikersbehoeften naast elkaar bestaan. 

De concept [handreiking lichte formaten](https://geonovum.github.io/geox/) heeft wel input hiervoor.

**Comment by frisopenninga** [comment]
Eens, subparagraaf toegevoegd met verwijzing naar handreiking
