### ISSUE TITLE
5.2: de term 'sub-optimalisatie' onduidelijk

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/wpungii#17]
In [paragraaf 5.2 Integrale sturing](https://geonovum.github.io/wpungii/#integrale-sturing) is de frase 'het gevaar van sub-optimalisatie' wat onduidelijk. Ik zou die bijzin weg laten en er van maken: "De huidige governance [...] is nog versnipperd. Zolang de sturing per silo is ingericht, ..."

**Comment by frisopenninga** [comment]
Overgenomen
