### ISSUE TITLE
Hfd 6 uitleg 'transparantie'

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/wpungii#18]
In [hoofdstuk 6](https://geonovum.github.io/wpungii/#NDTI) bij de laatste bullet point is de uitleg van het woord transparantie nog wat onduidelijk:

> hoe werken bewerkingen die tot beslissingen kunnen leiden

Wat denk ik bedoeld werd is iets als: hoe kwam de informatie/kennis tot stand op basis waarvan beslissingen zijn genomen? (je wilt mischien de term _algoritmes_ vermijden...)

**Comment by frisopenninga** [comment]
bewerkingen zijn breder dan alleen algoritmes, maar omvatten voor mij o.a. analyses (bijv. wat heb je met wat gecombineerd), modellen (bijv. welk rekenmodel heb je gebruikt) maar ook algoritmes. Dit toegevoegd in de korte uitleg bij traceerbaarheid en vervolgens bij transparantie naar verwezen
