### ISSUE TITLE
Hfd 6: data uit heterogene bronnen

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/wpungii#19]
In [hoofdstuk 6](https://geonovum.github.io/wpungii/#NDTI) zou ik ook benadrukken dat bij digital twins bij uitstek data uit allerlei heterogene bronnen (uit verschillende domeinen/disciplines) wordt gebruikt. Hier komt dat punt dus weer terug over het combineren van data, zie issue #9. 

Dit zou je zelfs als een vierde aspect in de tweede bullet list kunnen opnemen.

**Comment by frisopenninga** [comment]
Heb het toegevoegd aan 1e bullet van 2e opsomming, omdat meer heterogene bronnen ook voorbeeld is van bredere scope data, net als meer hoog-dynamische data,
