### ISSUE TITLE
Hfd 6 over hoog-dynamische data uitleggen

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/wpungii#20]
In [hoofdstuk 6](https://geonovum.github.io/wpungii/#NDTI) wordt gesproken van hoog-dynamische data. Dit mag m.i. wel iets meer uitgelegd worden. Gebruik van sensordata is bij uitstek een kenmerk van digital twins. Hier wordt het slechts in een bijzin genoemd ('bijvoorbeeld').

**Comment by frisopenninga** [comment]
Verwerkt
