### ISSUE TITLE
Hfd 6: output van digital twins

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/wpungii#21]
In [hoofdstuk 6](https://geonovum.github.io/wpungii/#NDTI) mis ik nog een ander aspect van digital twins: de output, i.e. hun invloed op de fysieke wereld. Dit kan indirect zijn, i.e. dat er beslissingen worden genomen op basis van de digital twin, maar het ingrijpen van een digital twin in de fysieke werkelijkheid kan ook direct zijn, manueel (omdat de gebruiker van de digital twin in de DT omgeving iets doet dat een effect heeft op de fysieke wereld, bijvoorbeeld een sprinkler aanzetten) of zelfs automatisch (op basis van sensordata en/of modellen, zonder menselijke tussenkomst). Het is misschien nog iets meer toekomstmuziek, maar wel een essentieel aspect van digital twins, dus deze zou ik ook noemen.

**Comment by frisopenninga** [comment]
Interessant aspect, toegevoegd.
