### ISSUE TITLE
Hfd 6: iets meer over visualisatie

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/wpungii#22]
In [hoofdstuk 6](https://geonovum.github.io/wpungii/#NDTI) kan het aspect visualisatie nog iets beter belicht worden. Dit wordt wel genoemd, maar niet toegelicht. Visualisatie heeft in digital twins een hele belangrijke rol en hierin moeten ook nog ontwikkelingen plaatsvinden. Deels noem je dit al in het stuk over verbeelding, maar denk ook aan VR, AR, serious gaming.

**Comment by frisopenninga** [comment]
Ik heb wat toelichting toegevoegd waarom visualisatieservices onderdeel zouden moeten worden van de NDTI (bijv. met oog op betrouwbare / eerlijke verbeelding van geplande ontwikkelingen). Dit omdat dit deel zich primair richt op de (bredere) scope van de afsprakenstelsels in zo'n NDTI en minder op de technische componenten/ontwikkelingen rond DT's.
