### ISSUE TITLE
Hfd 6: toevoeging eisen ethisch vlak

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/wpungii#23]
In [hoofdstuk 6](https://geonovum.github.io/wpungii/#NDTI) bij het punt eisen op ethisch vlak eventueel toevoegen: _Er zijn specifieke ethische afwegingen voor het gebruik van locatiedata, zoals beschreven door het W3C/OGC in [The Responsible Use of Spatial Data](https://www.w3.org/TR/responsible-use-spatial/)._

**Comment by frisopenninga** [comment]
Mooie verwijzing, toegevoegd
