### ISSUE TITLE
Hfd 7 federatief vs centraal 

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/wpungii#24]
[Hoofdstuk 7](https://geonovum.github.io/wpungii/#Architectuur) lezend bedacht ik een aspect van federatief/centraal dat nog niet geadresseerd wordt in het document: elke bronhouder zijn eigen data laten publiceren is wellicht minder kosteneffectief dan dit centraal te doen. Althans, dit hangt af van hoe je het technisch regelt, maar het is wel een aspect dat aandacht behoeft. Dit aspect zou zorgen kunnen oproepen bij bronhouders en softwareleveranciers.

**Comment by frisopenninga** [comment]
Toegevoegd
