### ISSUE TITLE
Hfd 8 punt over CRS

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/wpungii#25]
In [hoofdstuk 8](https://geonovum.github.io/wpungii/#Conclusie) zou ik het punt over werken met meerdere CRS omdraaien. Dan wordt het conform de SDWBP gesteld: 

_Gebruikers moeten kunnen profiteren van op het web gangbare CRS, en wanneer van toepassing ook in RD en ETRS89._

**Comment by frisopenninga** [comment]
Volledig omdraaien gaat me in scope van de NGII (met veel basisregistraties met wettelijke verplichtingen t.a.v. RD en ETRS) te ver, wel de webstandaarden prominenter genoemd.
