### ISSUE TITLE
2.4 samenhang over de grenzen van het geodomein heen

### ISSUE THREAD

**Issue by NielsHoffmann** [Geonovum/wpungii#26]
het zou misschien goed zijn om hier al expliciet te beschrijven dat een aanzet voor deze samenhang gelegd wordt via de NEN2660. 

De afstemming tussen de NEN3610 en de NEN2660 is er en de NEN2660 beschrijft ook andere domeinen, waardoor een deel van die samenhang daar in ieder geval mee geduid kan worden.

**Comment by frisopenninga** [comment]
Goed punt, verwerkt.
