### ISSUE TITLE
2.2 samenhang, harmoniseren

### ISSUE THREAD

**Issue by NielsHoffmann** [Geonovum/wpungii#27]
In de uitleg van harmoniseren kun je nu lezen dat het probleem opgelost zou worden als we een groot integraal (geharmoniseerd) model van de omgeving zouden maken.

Dit staat op enigszins gespannen voet met de wens voor 'federatieve structuren' zoals in 7 uitgelegd. Het zou mooi zijn als harmonisatie uitgelegd kan worden in termen van Domain Driven Design of 'High Cohesion, Loose Coupling'

**Comment by frisopenninga** [comment]
Op zich eens, maar ik kies ervoor om dit nu niet in de tekst te verwerken. Belangrijkste reden is dat het lastig is om op dit detailniveau aan te geven tot waar harmonisatie nog wel kan (een iets groter integraal model) en waar het een utopie wordt (een groots integraal model).
