### ISSUE TITLE
specifieke paragraaf nodig voor 'data/infrastructuur soevereiniteit' in relatie tot faang?

### ISSUE THREAD

**Issue by NielsHoffmann** [Geonovum/wpungii#28]
Er wordt op verschillende plekken wel wat gezegd over ethiek, europese ontwikkelingen, solid, e.d.
Ik vraag me af of de visie misschien expliciet een paragraaf verdient over de Nederlandse visie op een soevereine positie ten opzichte van 'big tech / faang'

**Comment by frisopenninga** [comment]
Voor de huidige insteek vind ik een aparte paragraaf tre ver gaan, maar ik heb wel de relatie met het Europese denken over publieke waarden (nadrukkelijk ook geformuleerd als antwoord op big tech) in o.a. de EU Data strategie wel explicieter aangehaald.
