### ISSUE TITLE
3.2 Ambitieuzere visie op CRS

### ISSUE THREAD

**Issue by Jochem-L** [Geonovum/wpungii#29]
Voor een upgrade van de GII mag de visie op de CRS-component (in overleg met de [NSGI](https://www.nsgi.nl/)) nog wel wat ambitieuzer in plaats van vooral de status quo voor de huidige best practices te beschrijven.

**3D:** De codes EPSG:4326 en EPSG:3857 zijn 2D codes. Het lijkt me beter om (ook) de 3D codes te vermelden en om ook een code voor RD+NAP (EPSG:7415) te vermelden en t.z.t. ook voor ETRS89+EVRS. De huidige links lopen bovendien dood, deze zouden moeten verwijzen naar: https://epsg.org/crs_4326/WGS-84.html en https://epsg.org/crs_3857/WGS-84-Pseudo-Mercator.html. 

**WGS84:** Het uitsluitend noemen van WGS84, het CRS van het Amerikaanse GNSS, en niet de CRSen van de andere GNSSen zoals het Europese Galileo is politiek niet neutraal. Omdat WGS84 desondanks in veel (de facto) standaarden gebruikt wordt, moet het wel genoemd worden. Het achterwege laten van het feit dat WGS84 afgeleid wordt van ITRS, het door de VN aanbevolen, wetenschappelijke CRS, vind ik echter onwenselijk. 

**ITRS:** Er is een wereldwijd bruikbaar CRS dat wel nauwkeurig is: ITRS. Voor nauwkeurig gebruik is het wel nodig om naar een specifieke ITRS-realisatie te verwijzen, bijvoorbeeld de meest recente realisatie: ITRF2014 (2D: EPSG:9000 / 3D: EPSG:7912). Daarnaast moet altijd een epoche (kalenderdatum) vermeld worden bij ieder coördinaat vanwege de tektonische beweging van Europa. Voor toepassingen waarin tijdsafhankelijke coördinaten onpraktisch zijn, kan een vast referentie-epoche gebruikt worden. In Europa is de conventie om voor ITRS op het referentie-epoche 1989.0 (01-01-1989) te gebruiken, dit is de definitie van ETRS89. Het zou goed zijn om in dit document de aanbeveling op te nemen om de meest recente ITRS-realisatie te gebruiken (ook als er eigenlijk om WGS84 gevraagd wordt) en om bij coördinaten altijd een epoche te vermelden. Daarbij kan verwezen worden naar de handreiking voor CRS-gebruik die momenteel geschreven wordt en eventueel aanvullende nog te schrijven adviezen van de NSGI, bijvoorbeeld over hoe om te gaan met tijdsafhankelijke coördinaten.

**EPSG-codes:** De EPSG-code voor webmercator (EPSG:3857) is op basis van WGS84. Dit is verwarrend wanneer men WGS84 gelijk stelt aan ITRS of ETRS89. De webmercator-projectie kan echter ook met een ETRS89- (of ITRS-)realisatie gebruikt worden. Hiervoor is echter niet een enkele EPSG-code, maar moet er een complexere aanduiding gebruikt worden, bijvoorbeeld: urn:ogc:def:crs,crs:EPSG::9067,cs:EPSG::4400,coordinateOperation:EPSG::3856,crs:EPSG::5709. Het lijkt me goed deze beperking van EPSG-codes en bovenstaande oplossing hiervoor te vermelden.

**RDNAPTRANS™:** De naam van de transformatieprocedure RDNAPTRANS is een geregistreerde merknaam. Het lijkt me goed om dat te vermelden (met TM) en dat software alleen toestemming krijgt om deze merknaam te gebruiken wanneer de transformatie 100% correct op de millimeter uitgevoerd wordt. Softwareproducenten en -gebruikers kunnen dit controleren met de [validatieservice](https://www.nsgi.nl/geodetische-infrastructuur/producten/programma-rdnaptrans/transformatievalidatie) van de NSGI.

**Comment by frisopenninga** [comment]
Voor de scope van deze white paper volg ik voorlopig de huidige SDOTW-BP, die gaan nog niet over 3D. Links wel gerepareerd. WGS84 is in spreektaal en deze toepassingen nu eenmaal een de facto standaard. Daar is inhoudelijk van alles op aan te merken, maar vanuit gebruiksoogpunt is het wel een belangrijk gegeven. ITRS zegt velen in die wereld nog niks, en is daarmee geen oplossing die in de praktijk soelaas biedt. Essentie van de Best Practices is juist om aan te sluiten bij de webwereld en daar gangbare standaarden, en niet om die te corrigeren of af te doen als onvoldoende of onjuist. RDNAPTRANS is nu van TM voorzien, verder linkt het WP al naar de officiële pagina's, dus daar kan men deze achtergrondinfo verder vinden.
