### ISSUE TITLE
3.3 Gebruikers verwachten samenhang en interoperabilteit ook over de grenzen van het geo-domein

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/wpungii#3]
Wat is eigenlijk het geo-domein? Wat mij betreft alle data waar een locatie een rol in speelt. Dat is ook in de bouwwereld en ook in assetmanagement.  Ik zou die daarom niet buiten de grens van het geo-domein of NGII plaatsen.

Beter is om de NGII uit te breiden naar, beter te laten aansluiten op, gebruik in het bouwdomein en assetmanagement-domein.

Andere titel: Gebruikers verwachten samenhang en interoperabiliteit van geo-domein met toepassingsdomeinen.

**Comment by frisopenninga** [comment]
Semantisch is het geo-domein inderdaad niet goed afgebakend, maar de meeste lezers zullen dit wel juist interpreteren. Voor mij ligt het in de lijn met de bij de Minister van BZK belegde verantwoordelijkheid als coördinerend bewindspersoon voor geo-informatie in Nederland. Vanuit die verantwoordelijkheid ligt er ook een beleidsverantwoordelijkheid voor de NGII. Oprekken naar alle domeinen met locatie sluit niet aan bij die afbakening.
