### ISSUE TITLE
H6: Laat NGII niet verstoffen!

### ISSUE THREAD

**Issue by emacgillavry** [Geonovum/wpungii#30]
Omarm NDTI als doorontwikkeling van de huidige NGII en zie het niet alleen als een "extensie".

Uit mijn eerste lezeing lijkt de relatie tussen NGII en NDTI wordt teveel als oud v. nieuw te worden gepresenteerd. Deze tweedeling schetst de huidige status van het NGII ten opzichte van het ideaal NDTI. Ook nu kunnen real-time services met bijvoorbeeld meteorologische data worden ontsloten in de NGII. Dat de basisregistraties nog niet real-time worden ontsloten is meer een uitvloeisel van de achterliggende processen, dan van de status van het NGII. 

> Zo biedt OpenStreetMap al jarenlang zogenaamde "[minutely updates](https://wiki.openstreetmap.org/wiki/Planet.osm/diffs)" op de brongegevens: zodra vrihjwilligers hun bijdragen hebben toegevoegd zijn deze wereldwijd beschikbaar en kunnen per minuut worden gedownload!

De hogere eisen op ethisch vlak zijn mijns inziens een gevolg van de huidige, ongemakkelijke relatie met meta-data ("teveel werk", "Wat moet je nu invullen?" en "Voor wie doe je het?") en het NGR ( "je kan er alles zoeken, maar niets vinden") en de aard van het merendeel van de data, die beschikbaar wordt gesteld. Immers: in het kleine wereldje van geo-specialisten speelt metadata nauwelijks een rol: we kennen nog altijd de herkomst en werkprocessen achter de data en weten bij wie we moeten zijn als er problemen in voorkomen. Daarom zijn de data voor mensen buiten de geo-wereld nu zo moeilijk te vinden. Meta data wordt nog niet gezien als uithangbord/reclame voor de rijke databronnen. Bovendien: locationele privacy is nauwelijks van belang bij de ontsluiting van geometriën van onze fysieke omgeving.

Web Processing Services (WPS) is al jaren een OGC specificatie die tot voor kort niet echt werkbaar was. Met de opkomst van cloud-services en niet-specifiek geo-APIs is het beschikbaar stellen van functionaliteit wel rendabel voor de aanbieder en werkbaar voor de afnemers.

Omarm NDTI, want het NGII biedt al **real-time data** en dit zal alleen maar meer worden. Maak duidelijk welke cloud-functionaliteit waar en onder welke voorwaarden beschikbaar zijn, bijvoorbeeld in een **algoritme-register** naar voorbeeld van [Amsterdam](https://algoritmeregister.amsterdam.nl/), positioneer metadata daarbij als hét **visitekaartje** van de data en splits paraplu-registraties (zoals BGT, BAG, BRT) daarbij op naar het niveau van de verschillende **objectklassen** (zoals snelwegen, lantaarnpalen, windmolens, adressen).

**Comment by frisopenninga** [comment]
NGII als oud en NDTI als nieuw is zeker niet de bedoeling, in het white paper proberen we NGII 1.0 als oud en NGII 2.0 als nieuw te positioneren, en vervolgens de relatie tussen NGII 2.0 en NDTI te schetsen. En hoewel dat onderscheid natuurlijk altijd enigszins arbitrair zal blijven, positioneren we de stap richting NGII 2.0 primair als systeemsprong op het gebied van data en de NDTI meer als systeemsprong op het gebied van functionaliteit / data analytics (o.a. tekstueel aangescherpt in conclusie). En het werkveld en de wereld ;-) zijn het beste af, wanneer we in staat zijn op beide systeemsprongen te maken.
