### ISSUE TITLE
4.1 Ontwikkeling: van losse bouwstenen naar een integraal antwoord op een informatiebehoefte

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/wpungii#4]
In feite is de beweging van vraag naar data, naar informatievraag naar kennisvraag.

De paragraaf geeft nog niet aan wat de consequentie hiervan is voor het ontsluiten en aanbieden van data. Bijvoorbeeld de DSO voegt middels beslisbomen een intelligentie laag toe aan data.  Ontologieen en AI kunnen worden ingezet voor informatie en kennisontsluiting.

**Comment by frisopenninga** [comment]
deze paragraaf was bedoeld als inleiding op de paragraaf erop: als onderbouwing waarom we nu een beweging naar nieuwe ontsluitingsvormen zien. Dat heb ik nu explicieter gemaakt.
