### ISSUE TITLE
1.1 data als grondstof + combineren van data

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/wpungii#9]
Ik  zou nog aan 1.1 willen toevoegen dat met het beschikbaar komen van open data, gebruikers deze data uit verschillende bronnen ook steeds meer willen gaan combineren. Nu er steeds meer data te verkrijgen is, zie je dat mensen die data ook willen gaan combineren / integreren om een vraag te beantwoorden. Je ziet dat bv veel in smart city / digital twin projecten. 

Daarbij lopen ze nu nog tegen interoperabiliteitsproblemen aan. Dat is dan weer iets voor een latere paragraaf. O.a. 3.1 en 4.1 sluiten hier al bij aan. Goed om dit punt dan in de inleiding in 1.1 te noemen.

**Comment by frisopenninga** [comment]
Tekst 1.1 aangepast, titel houd ik ongewijzigd, om 'm beknopt te houden.
